#!/bin/bash
#
#    deploy-fortigate
#    Copyright (C) 2016 Fortinet  Ltd.
#
#    Authors: Nicolas Thomss  <nthomasfortinet.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -ex
. /nova.rc

#Push image
 [ -f fortios.qcow2 ] || echo "you must download fortios.qcow2 in this directory"

openstack image show  "FGT VM64 1084" > /dev/null 2>&1 ||openstack image create --disk-format qcow2 --container-format bare  --public  "FGT VM64 1084"  --file fortios.qcow2
#http://docs.openstack.org/user-guide/cli-cheat-sheet.html

#Tried (ref http://docs.openstack.org/cli-reference/nova.html)

nova boot --image "FGT VM64 1084" FGT1 --key-name default --security-group default --flavor m1.small --user-data fgt-user-data.txt --config-drive=true --file license=FGVMUL0000075926.lic --nic net-name=private

IP=`nova floating-ip-create| awk '{print $4}' | grep -v IP`

nova floating-ip-associate FGT1 $IP


echo "you can access FGT admin@$IP"
#sudo iptables -t nat -A PREROUTING -p tcp --dport 4043 -j DNAT --to-destination 10.10.11.15:443
#sudo iptables -t nat -A PREROUTING -p tcp --dport 4022 -j DNAT --to-destination 10.10.11.15:22
