#!/bin/bash -e



folder=$HOME/cloud-images
mkdir -p $folder
URLS="http://cloud-images.ubuntu.com/trusty/current/trusty-server-cloudimg-amd64-disk1.img \
http://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img \
http://mirror.catn.com/pub/catn/images/qcow2/centos6.4-x86_64-gold-master.img \
http://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud.qcow2 \
http://download.cirros-cloud.net/0.3.4/cirros-0.3.4-x86_64-disk.img "

for URL in $URLS
do
FILENAME=${URL##*/}
if [ -f $folder/$FILENAME ];
then
    echo "$FILENAME already downloaded." 
else
    wget  -O  $folder/$FILENAME $URL
fi
done


echo "To download Windows image get there : https://cloudbase.it/windows-cloud-images/"
